### PR TITLE
Change EPL/BSD license headers to EPL/EDL

### PR DESCRIPTION
**Pull request by lossyrob**
This PR changes the previous copyright headers, which were dual EPL/BSD, to EDL.

### CODE REVIEW

**Comment by jodygarnett** [comment]
Looks good to me, resulting in a more consistent codebase

**Comment by bjornharrtell** [comment]
Since EDL is incompatible with GPL, might this change pose a problem for projects like GeoServer?@jodygarnett? From https://eclipse.org/legal/eplfaq.php#GPLCOMPATIBLE:

"Based upon the position of the Free Software Foundation, you may not combine EPL and GPL code in any scenario where linking exists between code made available under those licenses"

**Comment by mprins** [comment]
Note that the license in the pom.xml still states BSD license

**Comment by dr-jts** [comment]
@bjornharrtell That link refers to EPL.  EDL is apparently essentially BSD, and thus should not be a problem?  http://www.gnu.org/licenses/license-list.en.html#ModifiedBSD

**Comment by bjornharrtell** [comment]
Yes sorry I was getting confused. You are correct and it's clearly stated at https://eclipse.org/org/documents/edl-v10.php.

**Pull request merged**
